### PR TITLE
README: Change info to information everywhere

### PR DESCRIPTION
**Pull request by kborchers**
Trivial change used to test cla checker

### CODE REVIEW

**Comment by rxaviers** [comment]
:+1:

**Comment by kborchers** [comment]
Closing to try again. :pray:

**Comment by rxaviers** [comment]
I'm curious why are you closing and opening new PRs?

**Comment by rxaviers** [comment]
Edit: I'm curious why are you closing and opening new PRs instead of pushing new fixup commits to this same one?

**Comment by kborchers** [comment]
For exactly what just happened to me. I thought we had it because I did a re-delivery to the webhook and got the label. Closed, sent new PR, no label this time so still not quite right.

**Pull request closed without merging**
