### PR TITLE
Fix 57

### PR DESCRIPTION
**Pull request by rxaviers**
Not ready to be reviewed/merged.

### CODE REVIEW

**Comment by rxaviers** [comment]
Not ready to be reviewed/merged.

**Comment by rxaviers** [comment]
Problem:
- MessageFormat accepts `elements` property, which isn't listed by `argArray`.

**Comment by rxaviers** [comment]
Needs:
- Test;
- Benchmark the bundle output using lodash.omit.

**Comment by rxaviers** [comment]
Updates:
- Added tests.
- Ignored using any 3rd library (as considered above). Instead, used a simple `omit` code.
- Added `locale` and `elements` as two common properties that always need to be ignored from `otherProps` (the ones passed to SPAN).

**Comment by rxaviers** [comment]
This change prevents any ReactGlobalize components to forward specific `props` to the underlying `span` component. The specific `props` means individual `props` (like `variables` for `FormatMessage`, `unit` for `FormatRelativetime`, and so on), plus `props` that are common to any like `locale`, plus `elements` (ideally this should be removed for `FormatMessage` only, but I'm perventing it for all ReactGlobalize components for simplicity).

Would be great if someone could review it (cc @jzaefferer @kborchers @alunny @necolas). Actual change 806b8d44142730fc593db7a1280c86b561001ac0. I plan to merge and release as a patch release.

**Comment by rxaviers** [comment]
Merged and released as `0.3.9`. Any feedback are still welcome.

**Comment by rxaviers** [comment]
Amend fix released as `0.3.10`.

**Comment by necolas** [comment]
Thanks!

**Pull request closed without merging**
