### PR TITLE
Messages: Fix for production using Globalize runtime

### LINKED ISSUE #32: Broken messages component using Globalize runtime
I am unable to use the latest react-globalize on production (using Globalize runtime module). I get the following error:

```
TypeError: this.cldr is undefined
	aux[this.cldr.attributes.bundle] = {};
```

### PR DESCRIPTION
**Pull request by rxaviers**
Fixes #32

### CODE REVIEW

**Comment by rxaviers** [comment]
@alunny, the above fix works for me. It would be great if you could test it in your projects too before we land.

PS: We really need to get #1 addressed. :see_no_evil:

**Comment by rxaviers** [comment]
@alunny and @kborchers if there's no objection, I plan to land this and create a new patch release.

**Comment by kborchers** [comment]
I don't have a project to test in but reading it lgtm 👍

**Comment by kborchers** [comment]
Also agree on needing tests. If I can find any free time (lol) I would love to look into Intern or QUnit + https://github.com/airbnb/enzyme

**Pull request closed without merging**
