### PR TITLE
Upgrade react range to include 15.x

### PR DESCRIPTION
**Pull request by rxaviers**
Ref #55

### CODE REVIEW

**Comment by rxaviers** [comment]
This is a simple change that only updates react range to include `15.x` and also update `enzyme` to support react `15.x`. Tests pass.

**Comment by kborchers** [comment]
This LGTM. One comment/question that is somewhat related and could be rolled into this PR. Due to security concerns, however unlikely hijacking of a project is, should we stop using `^` in our dependency versions and only use specific versions? It does require a bit more maintenance when our deps update but it is safer. It also keeps us safe from improper use of semver if breaking changes are introduced in a patch release. Thoughts?

**Comment by rxaviers** [comment]
> should we stop using `^` in our dependency versions and only use specific versions

I assume you meant devDependencies, because this module doesn't specify direct dependencies (only devDependencies and peerDependencies). Anyway, I agree we could lock the devDependencies (updated the ones I've touched in a fixup commit b752f15 and all others could be addressed separately). About peerDependency, I think we should leave their ranges as they are (as large as possible) or users will start getting unnecessary warnings. Just let me know if I misunderstand you.

**Comment by rxaviers** [comment]
:+1:

**Comment by rxaviers** [comment]
One more thing... I plan to land this PR and release it as a patch release considering we didn't change anything in the library itself. Just let me know if you have any different suggestion pleae.

**Pull request closed without merging**
